CREATE WAREHOUSE wh_etl WITH WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE wh_bi  WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

SHOW PARAMETERS IN WAREHOUSE wh_bi;

ALTER WAREHOUSE wh_bi SET
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60,
  STATEMENT_TIMEOUT_IN_SECONDS = 300;

SELECT warehouse_name,
       COUNT(*) AS queries,
       AVG(queued_overload_time) AS avg_queued_ms,
       AVG(total_elapsed_time)   AS avg_elapsed_ms
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE start_time > DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY warehouse_name;

DROP WAREHOUSE wh_etl;
DROP WAREHOUSE wh_bi;