SELECT * FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(RESULT_LIMIT => 20));

SELECT query_id, user_name, execution_status, total_elapsed_time
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(RESULT_LIMIT => 20))
ORDER BY start_time DESC;

SELECT * from TABLE(sandbox.INFORMATION_SCHEMA.QUERY_HISTORY())