create warehouse my_warehouse
warehouse_type = 'SNOWPARK-OPTIMIZED'
;

drop warehouse my_warehouse
;


create warehouse if not exists PRACTICE_WH
warehouse_size = 'xsmall'
auto_suspend = 60
auto_resume = true
initially_suspended = true
;

USE WAREHOUSE PRACTICE_WH;
SELECT CURRENT_WAREHOUSE(), CURRENT_TIMESTAMP();

SELECT count(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;

ALTER WAREHOUSE PRACTICE_WH SET WAREHOUSE_SIZE = 'XSMALL';

DROP WAREHOUSE IF EXISTS PRACTICE_WH;


USE WAREHOUSE COMPUTE_WH;
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

SELECT count(distinct o_custkey) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

DESCRIBE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

SELECT * FROM TABLE(GET_QUERY_OPERATOR_STATS('01c72526-0104-b1f0-0005-363e000aa58e'));


-- WHERE句なし（全パーティションスキャンに近い）
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS group by o_orderkey;

-- 日付でフィルタ（プルーニングが効くか確認）
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
WHERE O_ORDERDATE = '1995-01-01';

-- GROUP BYを付けるとメタデータだけでは完結せず、ウェアハウスが必要になる
SELECT O_ORDERSTATUS, COUNT(*) 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS 
GROUP BY O_ORDERSTATUS;

-- GROUP BYを付けるとメタデータだけでは完結せず、ウェアハウスが必要になる
SELECT O_ORDERSTATUS, COUNT(*) 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS 
WHERE O_ORDERDATE = '1995-01-01'
GROUP BY O_ORDERSTATUS;


-- SF100で同じ比較（パーティション数が桁違いに増える）
SELECT O_ORDERSTATUS, COUNT(*) 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS 
WHERE O_ORDERDATE = '1995-01-01'
GROUP BY O_ORDERSTATUS;


-- SF100で同じ比較（パーティション数が桁違いに増える）
SELECT O_ORDERSTATUS, COUNT(*) 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS 
GROUP BY O_ORDERSTATUS;